name: Python CI
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.11"
        description: "Version of Python to use for testing environment"
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Update Pip
        run: pip install -U pip

      - uses: actions/cache@v4
        name: Define cache for dependencies
        with:
          path: .
          key: venv-${{ hashFiles('requirements**.txt') }}
          restore-keys: venv-${{ hashFiles('requirements**.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint
        run: pylint --fail-under=8 --recursive=yes --output-format=parseable --output=lintreport.txt .

      - name: Unit Test
        run: |
          coverage run -m pytest -v --junitxml=testresults.xml
          coverage xml
          sed -i 's@${{ github.workspace }}@/github/workspace@g' coverage.xml

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Vulnerability Scan
        uses: snyk/actions/python@master
        continue-on-error: true # Sometimes vulns aren't immediately fixable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --all-projects
