name: "Enforce Conventional Commit"

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.tainton.uk/actions/conventional-commits-check-action@v1.2.0
        with:
          commit-message: ${{ inputs.commit_message }}
