name: Python CI
on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pylint-exit
      - name: Lint
        run: pylint --recursive=yes --output-format=parseable --output=lintreport.txt . || pylint-exit $?
      - name: Unit Test
        run: |
          coverage run -m pytest -v --junitxml=testresults.xml
          coverage xml
          sed -i 's@${{ github.workspace }}@/github/workspace@g' coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
          SONAR_TOKEN: ${{ inputs.sonar_token }}
