name: Create Release
on:
  workflow_call:
    outputs:
      release_name:
        description: "Name of the created release"
        value: ${{ jobs.create_release.outputs.release_name }}

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Changes since last tag
        id: changes
        run: |
          CHANGES=$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --oneline)
          if [ -z "$CHANGES" ]; then exit 1; else exit 1; fi

      - name: Bump version and push tag
        if: steps.changes.outputs.any_changed == 'true'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # default_bump: minor
          default_bump: false

      - name: Create a GitHub release
        if: steps.changes.outputs.any_changed == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
